### ISSUE TITLE
Aspera

### ISSUE THREAD

**Issue by CocoConstant** [indexofire/pathongs#3]
hello~

There is a question about key file when I followed the aspera guidance you written. The `asperaweb_id_dsa.openssh` file is inexistent in my `~/.aspera/connect/etc/` directory. There is a similar file with the key file `aspera_tokenauth_id_sra`  in the directory.

![image](https://user-images.githubusercontent.com/110228235/184270470-92107ef2-c222-4aa1-bbd9-3f6931c56b34.png)  

best~

**Comment by indexofire** [comment]
aspera download part will be update, the original infomation is too old.
